//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationnewSE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobPost
    {
        public int Id { get; set; }
        public string jobTyoe { get; set; }
        public string Locationn { get; set; }
        public string StartTime { get; set; }
        public string EndTime { get; set; }
        public Nullable<int> Salary { get; set; }
        public string Title { get; set; }
        public string Designation { get; set; }
        public string RequiredSkills { get; set; }
        public string Department { get; set; }
    }
}
