//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationnewSE.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Database1Entities : DbContext
    {
        public Database1Entities()
            : base("name=Database1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<JobPost> JobPosts { get; set; }
        public virtual DbSet<ResumeCreation> ResumeCreations { get; set; }
        public virtual DbSet<ResumeCreation3> ResumeCreation3 { get; set; }
        public virtual DbSet<aaa> aaas { get; set; }
        public virtual DbSet<Application> Applications { get; set; }
    }
}
