//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationnewSE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResumeCreation3
    {
        public int RC3Id { get; set; }
        public string ResumeStatus { get; set; }
    }
}
